name: styliportfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.5.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.10.7
  firebase_app_check: ^0.2.2+7
  cloud_functions: ^4.7.6
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7
  firebase_crashlytics: ^3.5.7
  firebase_dynamic_links: ^5.5.7
  firebase_in_app_messaging: ^0.7.5+7
  firebase_app_installations: ^0.2.5+7
  firebase_ml_model_downloader: ^0.2.5+6
  firebase_performance: ^0.9.4+7
  firebase_database: ^10.5.7
  firebase_remote_config: ^4.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
